### PR TITLE
Add createFlag with multiple instructions

### PR DESCRIPTION
**Pull request by nachtm**
### Description:

This adds an overridden `createFlag` that takes in a list of instructions. All other `createFlag` functions only take in a single instruction, forcing users to manually concatenate multiple instructions together instead of using the `addInstructions` method already built-in to `CheckFlag`.

One note -- if I can change `CheckFlag`'s constructor to take in an `Iterable<String>` instead of a `List<String>`, then this function could take an iterable, which would be more general and easier to use. 

### Potential Impact:

Only a new method to use.

### Unit Test Approach:

There are no unit tests for `BaseCheck` at the moment -- adding them would probably be worthwhile. In the meantime, I tested this by modifying a couple of checks to use this constructor and running them on small datasets.

### Test Results:

All results look valid.

### CODE REVIEW

**Review by Bentleysb — APPROVED** [review]
Nice! I could have used this for the roundabout revamp.

**Review by sayas01 — APPROVED** [review]
Nice addition @nachtm !

**Comment by danielduhh** [comment]
Oh wow, I can't believe this didn't already exist !

**Review by danielduhh — APPROVED** [review]

**Comment by nachtm** [comment]
Thanks everyone!

**Pull request closed without merging**
